name: screenshot
on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  screenshot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TARGET_URL: ${{ github.event.issue.title }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: npm install

      - run: node main.mjs

      - run: |
          wget -qO gh.tar.gz https://github.com/cli/cli/releases/download/v2.100.0/gh_2.100.0_linux_amd64.tar.gz
          tar xf gh.tar.gz
          ./gh_2.100.0_linux_amd64/bin/gh issue comment "${{ github.event.issue.number }}" --body "$TARGET_URL" --attach ./screenshot.png
          ./gh_2.100.0_linux_amd64/bin/gh issue close "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
